# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformer < Formula
  desc "A go program that generates terraform using go templates ..."
  homepage "https://github.com/klaeff/terraformer"
  url "https://github.com/klaeff/terraformer/releases/download/1.0.5/terraformer_1.0.5_Darwin_x86_64.tar.gz"
  version "1.0.5"
  sha256 "5b93c035dc6cb2bb5453a3e711a81244c9c082d3daaaec7a11215dd74841d6f3"

  def install
    bin.install "terraformer"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#(bin)/terraformer --version"
  end
end
