# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformer < Formula
  desc "A go program that generates terraform using go templates ..."
  homepage "https://github.com/klaeff/terraformer"
  url "https://github.com/klaeff/terraformer/releases/download/1.0.6/terraformer_1.0.6_Darwin_x86_64.tar.gz"
  version "1.0.6"
  sha256 "2779fb9fbee3f1350f8e779ce4cb067881f44b86ec4ba994cbd78982ae1bd464"

  def install
    bin.install "terraformer"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#(bin)/terraformer --version"
  end
end
