# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformer < Formula
  desc "A go program that generates terraform using go templates ..."
  homepage "https://github.com/klaeff/terraformer"
  url "https://github.com/klaeff/terraformer/releases/download/1.0.4/terraformer_1.0.4_Darwin_x86_64.tar.gz"
  version "1.0.4"
  sha256 "bad6140f6964a596263cf7de1938ea234d3c2d72dcaf1252734d8c3fdc8c61ad"

  def install
    bin.install "terraformer"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
